<!DOCTYPE html>

<html>

<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />




<title>Práctica Dirigida 6</title>

<script src="site_libs/header-attrs-2.27/header-attrs.js"></script>
<script src="site_libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/flatly.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<style>h1 {font-size: 34px;}
       h1.title {font-size: 38px;}
       h2 {font-size: 30px;}
       h3 {font-size: 24px;}
       h4 {font-size: 18px;}
       h5 {font-size: 16px;}
       h6 {font-size: 12px;}
       code {color: inherit; background-color: rgba(0, 0, 0, 0.04);}
       pre:not([class]) { background-color: white }</style>
<script src="site_libs/jqueryui-1.13.2/jquery-ui.min.js"></script>
<link href="site_libs/tocify-1.9.1/jquery.tocify.css" rel="stylesheet" />
<script src="site_libs/tocify-1.9.1/jquery.tocify.js"></script>
<script src="site_libs/navigation-1.1/tabsets.js"></script>
<link href="site_libs/highlightjs-9.12.0/textmate.css" rel="stylesheet" />
<script src="site_libs/highlightjs-9.12.0/highlight.js"></script>

<style type="text/css">
  code{white-space: pre-wrap;}
  span.smallcaps{font-variant: small-caps;}
  span.underline{text-decoration: underline;}
  div.column{display: inline-block; vertical-align: top; width: 50%;}
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
  ul.task-list{list-style: none;}
    </style>

<style type="text/css">code{white-space: pre;}</style>
<script type="text/javascript">
if (window.hljs) {
  hljs.configure({languages: []});
  hljs.initHighlightingOnLoad();
  if (document.readyState && document.readyState === "complete") {
    window.setTimeout(function() { hljs.initHighlighting(); }, 0);
  }
}
</script>









<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
img {
  max-width:100%;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
summary {
  display: list-item;
}
details > summary > p:only-child {
  display: inline;
}
pre code {
  padding: 0;
}
</style>


<style type="text/css">
.dropdown-submenu {
  position: relative;
}
.dropdown-submenu>.dropdown-menu {
  top: 0;
  left: 100%;
  margin-top: -6px;
  margin-left: -1px;
  border-radius: 0 6px 6px 6px;
}
.dropdown-submenu:hover>.dropdown-menu {
  display: block;
}
.dropdown-submenu>a:after {
  display: block;
  content: " ";
  float: right;
  width: 0;
  height: 0;
  border-color: transparent;
  border-style: solid;
  border-width: 5px 0 5px 5px;
  border-left-color: #cccccc;
  margin-top: 5px;
  margin-right: -10px;
}
.dropdown-submenu:hover>a:after {
  border-left-color: #adb5bd;
}
.dropdown-submenu.pull-left {
  float: none;
}
.dropdown-submenu.pull-left>.dropdown-menu {
  left: -100%;
  margin-left: 10px;
  border-radius: 6px 0 6px 6px;
}
</style>

<script type="text/javascript">
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark the anchor link active (and if it's in a dropdown, also mark that active)
  var dropdown = menuAnchor.closest('li.dropdown');
  if (window.bootstrap) { // Bootstrap 4+
    menuAnchor.addClass('active');
    dropdown.find('> .dropdown-toggle').addClass('active');
  } else { // Bootstrap 3
    menuAnchor.parent().addClass('active');
    dropdown.addClass('active');
  }

  // Navbar adjustments
  var navHeight = $(".navbar").first().height() + 15;
  var style = document.createElement('style');
  var pt = "padding-top: " + navHeight + "px; ";
  var mt = "margin-top: -" + navHeight + "px; ";
  var css = "";
  // offset scroll position for anchor links (for fixed navbar)
  for (var i = 1; i <= 6; i++) {
    css += ".section h" + i + "{ " + pt + mt + "}\n";
  }
  style.innerHTML = "body {" + pt + "padding-bottom: 40px; }\n" + css;
  document.head.appendChild(style);
});
</script>

<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before, .tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "\e259";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "\e258";
  font-family: 'Glyphicons Halflings';
  border: none;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
  background-color: transparent;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<!-- code folding -->



<style type="text/css">

#TOC {
  margin: 25px 0px 20px 0px;
}
@media (max-width: 768px) {
#TOC {
  position: relative;
  width: 100%;
}
}

@media print {
.toc-content {
  /* see https://github.com/w3c/csswg-drafts/issues/4434 */
  float: right;
}
}

.toc-content {
  padding-left: 30px;
  padding-right: 40px;
}

div.main-container {
  max-width: 1200px;
}

div.tocify {
  width: 20%;
  max-width: 260px;
  max-height: 85%;
}

@media (min-width: 768px) and (max-width: 991px) {
  div.tocify {
    width: 25%;
  }
}

@media (max-width: 767px) {
  div.tocify {
    width: 100%;
    max-width: none;
  }
}

.tocify ul, .tocify li {
  line-height: 20px;
}

.tocify-subheader .tocify-item {
  font-size: 0.90em;
}

.tocify .list-group-item {
  border-radius: 0px;
}


</style>



</head>

<body>


<div class="container-fluid main-container">


<!-- setup 3col/9col grid for toc_float and main content  -->
<div class="row">
<div class="col-xs-12 col-sm-4 col-md-3">
<div id="TOC" class="tocify">
</div>
</div>

<div class="toc-content col-xs-12 col-sm-8 col-md-9">




<div class="navbar navbar-default  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-bs-toggle="collapse" data-target="#navbar" data-bs-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html">Material para pds</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li>
  <a href="index.html">Inicio</a>
</li>
<li>
  <a href="pd1.html">Práctica dirigida 1</a>
</li>
<li>
  <a href="pd2.html">Práctica dirigida 2</a>
</li>
<li>
  <a href="pd3.html">Práctica dirigida 3</a>
</li>
<li>
  <a href="pd4.html">Práctica dirigida 4</a>
</li>
<li>
  <a href="pd5.html">Práctica dirigida 5</a>
</li>
<li>
  <a href="pd6.html">Práctica dirigida 6</a>
</li>
<li>
  <a href="pd7.html">Práctica dirigida 7</a>
</li>
<li>
  <a href="pd8.html">Práctica dirigida 8</a>
</li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div id="header">



<h1 class="title toc-ignore">Práctica Dirigida 6</h1>

</div>


<p>FACULTAD DE CIENCIAS SOCIALES - PUCP</p>
<p>Curso: SOC285 - Estadística para el análisis sociológico 2</p>
<p>Semestre 2025 - 1</p>
<div id="qué-es-un-diseño-de-regresión-discontinua-rdd"
class="section level1">
<h1>¿Qué es un Diseño de Regresión Discontinua (RDD)?</h1>
<p>El Diseño de Regresión Discontinua (RDD, por sus siglas en inglés) es
una estrategia cuasi-experimental que permite evaluar el impacto causal
de una política o intervención cuando la asignación a un tratamiento se
basa en un umbral en una variable continua. La idea central es que los
individuos justo por encima y por debajo de este umbral son muy
similares en todo, excepto en que unos reciben el tratamiento y otros
no, lo que permite estimar efectos causales de manera robusta, como si
se tratara de un experimento natural.</p>
<div id="cómo-funciona" class="section level2">
<h2>¿Cómo funciona?</h2>
<p>El Diseño de Regresión Discontinua (RDD) se basa en la idea de que
cuando una política, programa o tratamiento se asigna en función de un
umbral en una variable continua (llamada <strong>running
variable</strong>), los individuos justo por encima y por debajo de ese
umbral son muy similares, excepto por el hecho de haber recibido o no el
tratamiento. Esto nos permite estimar un efecto causal, como si
tuviéramos un experimento natural.</p>
</div>
<div id="ejemplo" class="section level2">
<h2>Ejemplo</h2>
<p>Supongamos que un programa gubernamental otorga becas a estudiantes
con un puntaje de examen mayor o igual a 70. Los estudiantes que
obtienen 69 y 70 son muy parecidos en habilidades, pero solo los de 70
reciben la beca. Comparar el desempeño académico futuro de ambos grupos
nos permite estimar el impacto causal de la beca sobre el rendimiento
educativo.</p>
<p><img src="RDD1.png" /></p>
</div>
<div id="regresión" class="section level2">
<h2>Regresión</h2>
<p>Y𝑖​=α+β𝐷𝑖​+𝑓(𝑋𝑖)+ϵi</p>
<p>Donde:</p>
<ul>
<li><p>Y𝑖​ ​es la variable de resultado de interés para el individuo
𝑖.</p></li>
<li><p>α representa el valor esperado de la variable de resultado 𝑌
justo por debajo del umbral 𝑐</p></li>
<li><p>𝐷𝑖​ es la variable indicadora del tratamiento, donde 𝐷𝑖=1 si 𝑋𝑖
supera el umbral y 𝐷𝑖=0 en caso contrario.</p></li>
<li><p>𝑋𝑖 es la variable de asignación (o running variable), que
determina la elegibilidad para el tratamiento.</p></li>
<li><p>𝑓(𝑋𝑖) es una función flexible de la variable de asignación que
captura la tendencia de 𝑌𝑖 ​en ausencia del tratamiento (puede ser
lineal, cuadrática o de orden superior).</p></li>
<li><p>𝜖𝑖 ​es el término de error.</p></li>
<li><p>𝛽 es el parámetro clave de interés, que mide el efecto causal del
tratamiento en el umbral.​</p></li>
</ul>
</div>
<div id="por-qué-es-útil-para-la-sociología" class="section level2">
<h2>¿Por qué es útil para la sociología?</h2>
<p>En sociología, el RDD es valioso para evaluar el impacto de políticas
públicas, programas sociales y regulaciones. Por ejemplo, podríamos
analizar cómo una ley que establece un límite de edad para acceder a
beneficios sociales afecta la calidad de vida de los beneficiarios. Al
aprovechar decisiones administrativas que generan discontinuidades, los
sociólogos pueden obtener inferencias causales en contextos donde los
experimentos aleatorizados no son factibles.</p>
</div>
<div id="tabla-de-comparaciones-rdd-y-diff-in-diff"
class="section level2">
<h2><strong>Tabla de comparaciones RDD y Diff-in-Diff</strong></h2>
<table>
<colgroup>
<col width="33%" />
<col width="33%" />
<col width="33%" />
</colgroup>
<tbody>
<tr class="odd">
<td align="center"><strong>Característica</strong></td>
<td align="center"><strong>RDD</strong></td>
<td align="center"><strong>Diff-in-Diff</strong></td>
</tr>
<tr class="even">
<td align="center">Asignación del tratamiento</td>
<td align="center">Basada en un umbral (variable continua).</td>
<td align="center">Basada en grupos (tratamiento vs. control).</td>
</tr>
<tr class="odd">
<td align="center">Comparabilidad</td>
<td align="center">Individuos cerca del umbral.</td>
<td align="center">Grupos con tendencias paralelas.</td>
</tr>
<tr class="even">
<td align="center">Datos necesarios</td>
<td align="center">Datos en un punto específico (cerca del umbral).</td>
<td align="center">Datos longitudinales (antes y después).</td>
</tr>
<tr class="odd">
<td align="center">Ejemplo de uso</td>
<td align="center">Efecto de becas en estudiantes cerca del puntaje de
corte.</td>
<td align="center">Efecto de una política en una región vs. otra.</td>
</tr>
</tbody>
</table>
</div>
</div>
<div
id="how-do-extended-benefits-affect-unemployment-duration-a-regression-discontinuity-approach."
class="section level1">
<h1>How do extended benefits affect unemployment duration? A regression
discontinuity approach.</h1>
<p>En esta sesión se replicará el artículo de Rafael Lalive: “How do
extended benefits affect unemployment duration? A regression
discontinuity approach”. El autor buscar estudiar el efecto de un
programa que extendió la duración de los beneficios del desempleo de 30
semanas a 209 semanas en Austria. El punto de corte para recibir estos
beneficios era tener al menos 50 años y ser parte de las regiones
elegibles.</p>
<p>De esta forma tenemos 2 umbrales: edad y zona geográfica. El autor
decide quedarse con el segundo umbral como punto de corte porque las
compañías podían esperar a que sus empleados cumplan los 50 años para
darles de baja y así ellos puedan acceder al beneficio. En cambio, la
zona geográfica era un aspecto no manipulable. El autor se enfocará en
los individuos que viven cerca a la frontera entre las regiones tratadas
y no tratadas.</p>
<pre class="r"><code>library(rio)
library(tidyverse)</code></pre>
<pre><code>## Warning: package &#39;stringr&#39; was built under R version 4.4.3</code></pre>
<pre><code>## ── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
## ✔ dplyr     1.1.4     ✔ readr     2.1.5
## ✔ forcats   1.0.0     ✔ stringr   1.5.1
## ✔ ggplot2   3.5.1     ✔ tibble    3.2.1
## ✔ lubridate 1.9.3     ✔ tidyr     1.3.1
## ✔ purrr     1.0.2     
## ── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
## ✖ dplyr::filter() masks stats::filter()
## ✖ dplyr::lag()    masks stats::lag()
## ℹ Use the conflicted package (&lt;http://conflicted.r-lib.org/&gt;) to force all conflicts to become errors</code></pre>
<pre class="r"><code>data = import(&#39;releaseData.dta&#39;)</code></pre>
<div id="exploración-de-datos" class="section level2">
<h2>Exploración de datos</h2>
<div
id="datos-de-las-personas-que-pasan-el-umbral-de-edad-y-están-en-la-región-tratada."
class="section level3">
<h3>Datos de las personas que pasan el umbral de edad y están en la
región tratada.</h3>
<pre class="r"><code>c_1a = data %&gt;% 
  filter(age %in% c(50:53) &amp; female == 0 &amp; period == 1 &amp; tr == 1) %&gt;% 
  summarise(total = n(),
            promedio_edad = mean(age),
            promedio_distancia = mean(db),
            promedio_casado = mean(marr),
            promedio_construccion = mean(bau)) %&gt;% 
  mutate(tipo = &quot;Región tratados 50-53 años&quot;,
         sexo = &quot;Hombre&quot;)

c_1b = data %&gt;% 
  filter(age %in% c(50:53) &amp; female == 1 &amp; period == 1 &amp; tr == 1) %&gt;% 
  summarise(total = n(),
            promedio_edad = mean(age),
            promedio_distancia = mean(db),
            promedio_casado = mean(marr),
            promedio_construccion = mean(bau))%&gt;% 
  mutate(tipo = &quot;Región tratados 50-53 años&quot;,
         sexo = &quot;Mujer&quot;)</code></pre>
</div>
<div
id="datos-de-las-personas-que-no-pasan-el-umbral-de-edad-y-están-en-la-región-tratada"
class="section level3">
<h3>Datos de las personas que NO pasan el umbral de edad y están en la
región tratada:</h3>
<pre class="r"><code>c_2a= data %&gt;% 
  filter(age %in% c(46:49) &amp; female == 0 &amp; period == 1 &amp; tr == 1) %&gt;% 
  summarise(total = n(),
            promedio_edad = mean(age),
            promedio_distancia = mean(db),
            promedio_casado = mean(marr),
            promedio_construccion = mean(bau))%&gt;% 
  mutate(tipo = &quot;Región tratados 46-49 años&quot;,
         sexo = &quot;Hombre&quot;)

c_2b=data %&gt;% 
  filter(age %in% c(46:49) &amp; female == 1 &amp; period == 1 &amp; tr == 1) %&gt;% 
  summarise(total = n(),
            promedio_edad = mean(age),
            promedio_distancia = mean(db),
            promedio_casado = mean(marr),
            promedio_construccion = mean(bau))%&gt;% 
  mutate(tipo = &quot;Región tratados 46-49 años&quot;,
         sexo = &quot;Mujer&quot;)</code></pre>
</div>
<div
id="datos-de-las-personas-que-pasan-el-umbral-de-edad-y-no-están-en-la-región-tratada"
class="section level3">
<h3>Datos de las personas que pasan el umbral de edad y NO están en la
región tratada:</h3>
<pre class="r"><code>c_3a=data %&gt;% 
  filter(age %in% c(50:53) &amp; female == 0 &amp; period == 1 &amp; tr == 0) %&gt;% 
  summarise(total = n(),
            promedio_edad = mean(age),
            promedio_distancia = mean(db),
            promedio_casado = mean(marr),
            promedio_construccion = mean(bau))%&gt;% 
  mutate(tipo = &quot;Región NO tratados 50-53 años&quot;,
         sexo = &quot;Hombre&quot;)

c_3b =data %&gt;% 
  filter(age %in% c(50:53) &amp; female == 1 &amp; period == 1 &amp; tr == 0) %&gt;% 
  summarise(total = n(),
            promedio_edad = mean(age),
            promedio_distancia = mean(db),
            promedio_casado = mean(marr),
            promedio_construccion = mean(bau))%&gt;% 
  mutate(tipo = &quot;Región NO tratados 50-53 años&quot;,
         sexo = &quot;Mujer&quot;)</code></pre>
</div>
<div id="unión-de-los-descriptivos" class="section level3">
<h3>Unión de los descriptivos:</h3>
<pre class="r"><code>rbind(c_1a,c_1b,c_2a,c_2b,c_3a,c_3b) %&gt;% 
  gather(parametro,valor,-c(&quot;sexo&quot;,&quot;tipo&quot;)) %&gt;% 
  arrange(sexo) %&gt;% 
  mutate(valor = round(valor,2)) %&gt;% 
  spread(tipo,valor) %&gt;% 
  View()</code></pre>
</div>
<div
id="promedio-de-semanas-de-desempleo-entre-ambos-grupos-46-49-y-50-53-dentro-de-la-región-tratada-en-un-gráfico"
class="section level3">
<h3>Promedio de semanas de desempleo entre ambos grupos (46-49 y 50-53)
dentro de la región tratada en un gráfico:</h3>
<div id="hombres" class="section level4">
<h4>Hombres:</h4>
<pre class="r"><code>toPlot1 = data %&gt;%
  filter(female == 0 &amp; tr == 1) %&gt;%
  mutate(color_age = ifelse(age&gt;=50,1,0)) %&gt;% 
  group_by(color_age,age) %&gt;% 
  summarise(promedio = mean(unemployment_duration))</code></pre>
<pre><code>## `summarise()` has grouped output by &#39;color_age&#39;. You can override using the
## `.groups` argument.</code></pre>
<pre class="r"><code>ggplot(toPlot1, aes(x = age, y = promedio, color =color_age )) +
  geom_line()+
  geom_point()+
  geom_vline(xintercept = 50, colour = &quot;red&quot;) + 
  labs(x = &quot;Edad&quot;, y = &quot;Semanas de desempleo&quot;) + 
  guides(color = FALSE)+
  theme_bw()</code></pre>
<pre><code>## Warning: The `&lt;scale&gt;` argument of `guides()` cannot be `FALSE`. Use &quot;none&quot; instead as
## of ggplot2 3.3.4.
## This warning is displayed once every 8 hours.
## Call `lifecycle::last_lifecycle_warnings()` to see where this warning was
## generated.</code></pre>
<p><img src="pd6_files/figure-html/unnamed-chunk-6-1.png" width="672" /></p>
</div>
<div id="mujeres" class="section level4">
<h4>Mujeres:</h4>
<pre class="r"><code>toPlot2 = data %&gt;%
  filter(female == 1 &amp; tr == 1) %&gt;%
  mutate(color_age = ifelse(age&gt;=50,1,0)) %&gt;% 
  group_by(color_age,age) %&gt;% 
  summarise(promedio = mean(unemployment_duration))</code></pre>
<pre><code>## `summarise()` has grouped output by &#39;color_age&#39;. You can override using the
## `.groups` argument.</code></pre>
<pre class="r"><code>ggplot(toPlot2, aes(x = age, y = promedio, color =color_age )) +
  geom_line()+
  geom_point()+
  geom_vline(xintercept = 50, colour = &quot;red&quot;) + 
  labs(x = &quot;Edad&quot;, y = &quot;Semanas de desempleo&quot;) + 
  guides(color = FALSE)+
  theme_bw()</code></pre>
<p><img src="pd6_files/figure-html/unnamed-chunk-7-1.png" width="672" /></p>
</div>
<div id="comparación-entre-región-control-y-no-control-por-sexo"
class="section level4">
<h4>Comparación entre región control y no control por sexo:</h4>
<pre class="r"><code>toPlot3 &lt;- data %&gt;%
  filter(age %in% c(50:53)) %&gt;%  # Filtrar edades entre 50 y 53
  group_by(tr, female, age) %&gt;%  # Agrupar por tr, female y age
  mutate(
    tr = factor(tr, levels = c(0, 1), labels = c(&quot;Región no tratada&quot;, &quot;Región tratada&quot;)),  # Etiquetar tr
    female = factor(female, levels = c(0, 1), labels = c(&quot;Hombre&quot;, &quot;Mujer&quot;))  # Etiquetar female
  ) %&gt;%
  summarise(promedio = mean(unemployment_duration))  # Calcular el promedio de duración del desempleo</code></pre>
<pre><code>## `summarise()` has grouped output by &#39;tr&#39;, &#39;female&#39;. You can override using the
## `.groups` argument.</code></pre>
<pre class="r"><code># Crear el gráfico
ggplot(toPlot3, aes(x = age, y = promedio, group = tr, color = tr)) +
  geom_line() +  # Líneas
  geom_point() +  # Puntos
  facet_wrap(~female) +  # Dividir por sexo
  labs(
    x = &quot;Edad&quot;, 
    y = &quot;Semanas de desempleo&quot;, 
    color = &quot;Región&quot;  # Cambiar el título de la leyenda de color
  ) +
  theme_bw()  # Usar un tema limpio</code></pre>
<p><img src="pd6_files/figure-html/unnamed-chunk-8-1.png" width="672" /></p>
</div>
</div>
</div>
<div id="modelos-de-regresión" class="section level2">
<h2>Modelos de regresión</h2>
<div id="hombres-1" class="section level3">
<h3>Hombres</h3>
<div id="modelo-de-regresión---umbral-de-edad" class="section level4">
<h4>Modelo de regresión - umbral de edad:</h4>
<pre class="r"><code>datos_regresion1 = data %&gt;% 
  filter(female == 0 &amp; period == 1 &amp; tr == 1)

modelo_hombres1 = lm(unemployment_duration ~ as.factor(age50), data = datos_regresion1)

summary(modelo_hombres1)</code></pre>
<pre><code>## 
## Call:
## lm(formula = unemployment_duration ~ as.factor(age50), data = datos_regresion1)
## 
## Residuals:
##    Min     1Q Median     3Q    Max 
## -28.98 -20.72 -12.31  -3.12 506.34 
## 
## Coefficients:
##                   Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)        14.5192     0.8224   17.66   &lt;2e-16 ***
## as.factor(age50)1  14.6047     1.1761   12.42   &lt;2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 58 on 9732 degrees of freedom
## Multiple R-squared:  0.0156, Adjusted R-squared:  0.0155 
## F-statistic: 154.2 on 1 and 9732 DF,  p-value: &lt; 2.2e-16</code></pre>
<p>Incrementar los beneficios de desempleo hasta en 209 semanas prolongó
la duración de desempleo en 14.6 semanas en promedio entre hombres de 50
a 53 años comparados a hombres entre 46-49 años de edad.</p>
</div>
<div id="modelo-de-regresión---umbral-de-zona-geográfica"
class="section level4">
<h4>Modelo de regresión - umbral de zona geográfica:</h4>
<pre class="r"><code>datos_regresion2 = data %&gt;% 
  mutate(db_0 = ifelse(db&gt;=0,1,0)) %&gt;% 
  filter(female == 0 &amp; period == 1 &amp; age %in% c(50:53))

modelo_hombres2 = lm(unemployment_duration ~ db_0, data = datos_regresion2)

summary(modelo_hombres2)</code></pre>
<pre><code>## 
## Call:
## lm(formula = unemployment_duration ~ db_0, data = datos_regresion2)
## 
## Residuals:
##    Min     1Q Median     3Q    Max 
## -32.10 -20.56  -9.81  -1.97 492.17 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)   12.517      2.099   5.962 3.24e-09 ***
## db_0          19.726      3.410   5.785 9.18e-09 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 58.06 on 1230 degrees of freedom
## Multiple R-squared:  0.02649,    Adjusted R-squared:  0.0257 
## F-statistic: 33.47 on 1 and 1230 DF,  p-value: 9.176e-09</code></pre>
<p>En las regiones donde se incrementó los beneficios de desempleo hasta
en 209 semanas, hubo un aumento promedio de 19.7 semanas de desempleo en
hombres entre 50-53 años de edad.</p>
</div>
</div>
<div id="mujeres-1" class="section level3">
<h3>Mujeres</h3>
<div id="modelo-de-regresión---umbral-de-edad-1" class="section level4">
<h4>Modelo de regresión - umbral de edad:</h4>
<pre class="r"><code>datos_regresion3 = data %&gt;% 
  filter(female == 1 &amp; period == 1 &amp; tr == 1)

modelo_mujeres1 = lm(unemployment_duration ~as.factor(age50), data = datos_regresion3)

summary(modelo_mujeres1)</code></pre>
<pre><code>## 
## Call:
## lm(formula = unemployment_duration ~ as.factor(age50), data = datos_regresion3)
## 
## Residuals:
##    Min     1Q Median     3Q    Max 
## -89.25 -60.54 -16.82  27.53 499.76 
## 
## Coefficients:
##                   Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)         21.233      1.733   12.26   &lt;2e-16 ***
## as.factor(age50)1   68.158      2.214   30.79   &lt;2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 81.14 on 5657 degrees of freedom
## Multiple R-squared:  0.1435, Adjusted R-squared:  0.1434 
## F-statistic: 947.8 on 1 and 5657 DF,  p-value: &lt; 2.2e-16</code></pre>
<p>Incrementar los beneficios de desempleo hasta en 209 semanas prolongó
la duración de desempleo en 68.1 semanas en promedio entre mujeres de 50
a 53 años comparados a mujeres entre 46-49 años de edad.</p>
</div>
<div id="modelo-de-rgeresión---umbral-de-zona-geográfica"
class="section level4">
<h4>Modelo de rgeresión - umbral de zona geográfica:</h4>
<pre class="r"><code>datos_regresion4 = data %&gt;% 
  mutate(db_0 = ifelse(db&gt;=0,1,0)) %&gt;% 
  filter(female == 1 &amp; period == 1 &amp; age %in% c(50:53))

modelo_mujeres4 = lm(unemployment_duration ~ db_0, data = datos_regresion4)

summary(modelo_mujeres4)</code></pre>
<pre><code>## 
## Call:
## lm(formula = unemployment_duration ~ db_0, data = datos_regresion4)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -112.13  -30.42  -12.75   31.00  500.41 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)   30.562      4.837   6.319 4.69e-10 ***
## db_0          81.714      6.617  12.349  &lt; 2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 87.33 on 698 degrees of freedom
## Multiple R-squared:  0.1793, Adjusted R-squared:  0.1781 
## F-statistic: 152.5 on 1 and 698 DF,  p-value: &lt; 2.2e-16</code></pre>
<p>En las regiones donde se incrementó los beneficios de desempleo hasta
en 209 semanas, hubo un aumento promedio de 81.7 semanas de desempleo en
mujeres entre 50-53 años de edad.</p>
</div>
</div>
</div>
</div>



</div>
</div>

</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.odd').parent('tbody').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- tabsets -->

<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open');
  });
});
</script>

<!-- code folding -->

<script>
$(document).ready(function ()  {

    // temporarily add toc-ignore selector to headers for the consistency with Pandoc
    $('.unlisted.unnumbered').addClass('toc-ignore')

    // move toc-ignore selectors from section div to header
    $('div.section.toc-ignore')
        .removeClass('toc-ignore')
        .children('h1,h2,h3,h4,h5').addClass('toc-ignore');

    // establish options
    var options = {
      selectors: "h1,h2,h3",
      theme: "bootstrap3",
      context: '.toc-content',
      hashGenerator: function (text) {
        return text.replace(/[.\\/?&!#<>]/g, '').replace(/\s/g, '_');
      },
      ignoreSelector: ".toc-ignore",
      scrollTo: 0
    };
    options.showAndHide = true;
    options.smoothScroll = true;

    // tocify
    var toc = $("#TOC").tocify(options).data("toc-tocify");
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
